language: "ko-KR"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: false
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches: [".*"]
chat:
  auto_reply: true
