server:
  port: 8080
  tomcat:
    mbean-registry:
      enabled: true
    max-http-form-post-size: 2MB

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  profiles:
    default: local

  config:
    import:
      - security/smtp.yml
      - security/oauth.yml
      - security/jwt.yml
      - security/db.yml
      - security/slack.yml
      - security/aws.yml

  application:
    name: ah-madda

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    token-uri: ${oauth.google.token-uri}
    user-uri: ${oauth.google.user-uri}
    connect-timeout: 3000
    read-timeout: 5000

smtp:
  google:
    host: ${secrets.smtp.google.host}
    port: 587
    username: ${secrets.smtp.google.username}
    password: ${secrets.smtp.google.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 5000

  aws:
    host: ${secrets.smtp.aws.host}
    port: 587
    username: ${secrets.smtp.aws.username}
    password: ${secrets.smtp.aws.password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      primaryEmail:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        slowCallDurationThreshold: 5s
        slowCallRateThreshold: 50
        waitDurationInOpenState: 2m
        permittedNumberOfCallsInHalfOpenState: 3

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /specification
    operations-sorter: method
    persist-authorization: true

management:
  metrics:
    enable:
      all: false
  endpoints:
    web:
      exposure:
        include:
          - health
    jmx:
      exposure:
        exclude: '*'

slack:
  bot-token: ${slack.bot-token}
  channel-id: ${slack.channel-id}
  post-message-url: ${slack.post-message-url}
  connect-timeout: 3000
  read-timeout: 5000
