spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.prod.host}:${db.prod.port}/${db.prod.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.prod.username}
    password: ${db.prod.password}

  jpa:
    hibernate:
      ddl-auto: update  # TODO. 추후 v1.0.0에서 validate로 변경

  cloud:
    aws:
      region:
        static: ap-northeast-2

jwt:
  secret-key: ${jwt.prod.secret-key}
  access-expiration: ${jwt.prod.access-expiration}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
    - https://ahmadda.com
    - https://prod.ahmadda.com

notification:
  redirect-url-prefix: https://ahmadda.com/event/

aws:
  s3:
    region: ${aws.prod.s3.region}
    bucket: ${aws.prod.s3.bucket}
    folder: ${aws.prod.s3.folder}

management:
  metrics:
    enable:
      system.cpu.usage: true
      jvm.memory.used: true
      jvm.memory.max: true
      http.server.requests: true
      tomcat.threads: true
      app.health.status: true
      executor: true
      hikaricp.connections.active: true
      hikaricp.connections.pending: true
      hikaricp.connections.max: true
      hikaricp.connections.timeout: true
      logback.events: true
  cloudwatch:
    metrics:
      export:
        enabled: true
        step: 1m
        namespace: EC2/ahmadda-api
