spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.prod.host}:${db.prod.port}/${db.prod.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.prod.username}
    password: ${db.prod.password}

  jpa:
    hibernate:
      ddl-auto: update  # TODO. 추후 v1.0.0에서 validate로 변경

jwt:
  secret-key: ${jwt.prod.secret-key}
  access-expiration: ${jwt.prod.access-expiration}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
    - https://ahmadda.com

management:
  metrics:
    instrumentation:
      http:
        server:
          enabled: true

    export:
      cloudwatch:
        enabled: true
        namespace: EC2/ahmadda-api
        step: 1m

logging:
  level:
    io.micrometer.cloudwatch2: DEBUG
    software.amazon.awssdk: DEBUG

notification:
  redirect-url-prefix: https://ahmadda.com/event/
