spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        detector:
          enabled: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

client:
  url: http://localhost:5173

jwt:
  secret-key: ${jwt.local.secret-key}
  access-expiration: ${jwt.local.access-expiration}

mail:
  mock: true
