server:
  port: 8080
  tomcat:
    mbean-registry:
      enabled: true
    max-http-form-post-size: -1

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  profiles:
    default: local

  config:
    import:
      - security/smtp.yml
      - security/oauth.yml
      - security/jwt.yml
      - security/db.yml
      - security/slack.yml
      - security/aws.yml

  application:
    name: ah-madda

  mail:
    host: smtp.gmail.com
    port: 587
    username: amadda.mailbot
    password: ${smtp.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 5000

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    token-uri: ${oauth.google.token-uri}
    user-uri: ${oauth.google.user-uri}
    connect-timeout: 3000
    read-timeout: 5000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /specification
    operations-sorter: method
    persist-authorization: true

management:
  metrics:
    enable:
      all: false
  endpoints:
    web:
      exposure:
        include:
          - health
    jmx:
      exposure:
        exclude: '*'
  health:
    db:
      enabled: false
    mail:
      enabled: false

slack:
  bot-token: ${slack.bot-token}
  channel-id: ${slack.channel-id}
  post-message-url: ${slack.post-message-url}
  connect-timeout: 3000
  read-timeout: 5000
