server:
  port: 8080

spring:
  profiles:
    default: local

  config:
    import:
      - security/smtp.yml
      - security/oauth.yml
      - security/jwt.yml
      - security/db.yml

  application:
    name: ah-madda

  mail:
    host: smtp.gmail.com
    port: 587
    username: amadda.mailbot
    password: ${smtp.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 1000
          starttls:
            enable: true

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    redirect-uri: ${oauth.google.redirect-uri}
    token-uri: ${oauth.google.token-uri}
    user-uri: ${oauth.google.user-uri}
    connect-timeout: 3000
    read-timeout: 5000
