spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahmadda?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ahmadda
    password: 1234

  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    show-sql: true
    properties:
      hibernate:
        detector:
          enabled: true
    hibernate:
      ddl-auto: validate

  cloud:
    aws:
      s3:
        region: ap-northeast-2

jwt:
  secret-key: ${jwt.local.secret-key}
  access-expiration: ${jwt.local.access-expiration}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173

notification:
  redirect-url-prefix: http://localhost:5173/event/

mail:
  mock: true

push:
  mock: true

slack:
  mock: true

aws:
  s3:
    mock: true
    bucket: ${aws.local.s3.bucket}
    folder: ${aws.local.s3.folder}
