server:
  port: 8080

spring:
  profiles:
    default: local

  config:
    import:
      - security/smtp.yml

  application:
    name: ah-madda

  mail:
    host: smtp.gmail.com
    port: 587
    username: amadda.mailbot
    password: ${smtp.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 1000
          starttls:
            enable: true
