server:
  port: 8080

spring:
  profiles:
    default: local

  config:
    import:
      - security/oauth.yml
      - security/jwt.yml

  application:
    name: ah-madda

oauth:
  google:
    client-id: ${oauth.google.client-id}
    client-secret: ${oauth.google.client-secret}
    redirect-uri: ${oauth.google.redirect-uri}
    token-uri: ${oauth.google.token-uri}
    user-uri: ${oauth.google.user-uri}
    connect-timeout: 3000
    read-timeout: 5000
