spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        detector:
          enabled: true

jwt:
  secret-key: ${jwt.local.secret-key}
  access-expiration: ${jwt.local.access-expiration}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173

notification:
  redirect-url-prefix: http://localhost:5173/event/

mail:
  mock: true

push:
  mock: true

slack:
  mock: true

aws:
  s3:
    mock: true
    region: ap-northeast-2
    bucket: ${aws.local.s3.bucket}
    folder: ${aws.local.s3.folder}
