version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
