name: BE Prod Deploy On Hotfix

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  setup:
    if: startsWith(github.event.head_commit.message, 'hotfix')
    runs-on: ubuntu-22.04-arm

    outputs:
      image-tag: ${{ steps.extract.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.BE_SUBMODULE_TOKEN }}

      - name: Get latest v{head}.{yearweek} tag
        id: base
        run: |
          git fetch --tags

          latest_tag=$(git tag -l 'v*.*' | sort -V | tail -n 1)
          echo "latest_tag=$latest_tag"
          
          head=$(echo "$latest_tag" | cut -d'.' -f1 | sed 's/v//')
          yearweek=$(echo "$latest_tag" | cut -d'.' -f2)

          echo "head=$head" >> $GITHUB_OUTPUT
          echo "yearweek=$yearweek" >> $GITHUB_OUTPUT
          echo "base_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Determine next build number
        id: extract
        run: |
          prefix="be-v${{ steps.base.outputs.head }}.${{ steps.base.outputs.yearweek }}"

          latest_hotfix=$(git tag -l "${prefix}.*" | sort -V | tail -n 1)

          if [ -z "$latest_hotfix" ]; then
            build=2
          else
            last_build=$(echo "$latest_hotfix" | awk -F. '{print $3}')
            build=$((last_build + 1))
          fi

          version="${prefix}.${build}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Using version: $version"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests
        working-directory: ./server
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PROD_DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_DEPLOY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: amadda/ahmadda_server:${{ steps.extract.outputs.version }}

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag "${{ steps.extract.outputs.version }}"
          git push origin "${{ steps.extract.outputs.version }}"
