name: BE Prod Deploy On Hotfix

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

permissions: write-all

jobs:
  setup:
    if: startsWith(github.event.head_commit.message, 'hotfix')
    runs-on: ubuntu-22.04-arm

    outputs:
      image-tag: ${{ steps.calc.outputs.version }}

    steps:
      - name: Checkout (for tagging)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest be tag
        id: latest
        run: |
          git fetch --tags

          latest_be_tag=$(git tag -l 'v*.*.*+be.*' | sort -V | tail -n 1)

          base=$(echo "$latest_be_tag" | sed -E 's/^v([0-9]+\.[0-9]+\.[0-9]+)\+be\..*/\1/')

          head=$(echo "$base" | cut -d'.' -f1)
          yearweek=$(echo "$base" | cut -d'.' -f2)
          common_build=$(echo "$base" | cut -d'.' -f3)

          echo "head=$head" >> $GITHUB_OUTPUT
          echo "yearweek=$yearweek" >> $GITHUB_OUTPUT
          echo "common_build=$common_build" >> $GITHUB_OUTPUT

      - name: Calculate next BE build version
        id: calc
        run: |
          git fetch --tags

          head="${{ steps.latest.outputs.head }}"
          yearweek="${{ steps.latest.outputs.yearweek }}"
          common="${{ steps.latest.outputs.common_build }}"

          prefix="v${head}.${yearweek}.${common}+be"

          matching_tags=$(git tag -l "${prefix}.*")
          if [[ -z "$matching_tags" ]]; then
            next_be_build=1
          else
            last_be_build=$(echo "$matching_tags" | awk -F. '{print $2}' | awk -F'+' '{print $2}' | awk -F. '{print $2}' | sort -n | tail -n 1)

            next_be_build=$((last_be_build + 1))
          fi

          version="${prefix}.${next_be_build}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Using version: $version"

      - name: Create and push Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          tag="${{ steps.calc.outputs.version }}"
          git tag "$tag"
          git push origin "$tag"

      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.BE_SUBMODULE_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run tests
        working-directory: ./server
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PROD_DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.PROD_DOCKERHUB_DEPLOY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: amadda/ahmadda_server:${{ steps.calc.outputs.version }}

  deploy:
    needs: setup
    runs-on:
      - self-hosted
      - prod

    steps:
      - name: Set tag name from setup output
        run: echo "TAG=${{ needs.setup.outputs.image-tag }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          sudo docker login \
            --username ${{ secrets.PROD_DOCKERHUB_DEPLOY_USERNAME }} \
            --password ${{ secrets.PROD_DOCKERHUB_DEPLOY_TOKEN }}

      - name: Stop existing container and pull latest image
        run: |
          if sudo docker inspect ahmadda-prod-server &>/dev/null; then
            sudo docker stop ahmadda-prod-server || true
            sudo docker rm -f ahmadda-prod-server || true
            sudo docker image prune -af || true
          fi
          sudo docker pull amadda/ahmadda_server:$TAG

      - name: Run container
        run: |
          sudo docker run -v /home/ubuntu/app/logs:/app/logs \
            --name ahmadda-prod-server \
            --restart unless-stopped \
            -p 80:8080 \
            -e PROFILE=prod \
            -d amadda/ahmadda_server:$TAG
