name: BE Prod Deploy On Pull Request (Test)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on:
      - self-hosted
      - prod

    outputs:
      s3_key: ah-madda/codedeploy/ahmadda-server-prod-${{ steps.set_version.outputs.version }}.zip
      release_tag: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.BE_SUBMODULE_TOKEN }}

      - name: Set temporary version for testing
        id: set_version
        run: echo "version=test-codedeploy" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run tests
        working-directory: ./server
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Build with Gradle
        working-directory: ./server
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Create deployment package
        run: |
          mkdir deploy
          cp server/build/libs/*[!plain].jar deploy/ahmadda-server-prod.jar
          cp codedeploy/be/appspec.yml deploy/
          cp -r codedeploy/be/scripts/ deploy/
          cd deploy
          zip -r ../ahmadda-server-prod-${{ steps.set_version.outputs.version }}.zip .
          cd ..

      - name: Upload to S3
        run: |
          aws s3 cp \
            ahmadda-server-prod-${{ steps.set_version.outputs.version }}.zip \
            s3://techcourse-project-2025/ah-madda/codedeploy/ahmadda-server-prod-${{ steps.set_version.outputs.version }}.zip

  deploy:
    needs: build
    runs-on:
      - self-hosted
      - prod

    steps:
      - name: Start AWS CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name ahmadda-code-deploy-ec2 \
            --deployment-group-name ahmadda-code-deploy-alb \
            --s3-location bucket=techcourse-project-2025,key=${{ needs.build.outputs.s3_key }},bundleType=zip \
            --description "Test deployment ${{ needs.build.outputs.release_tag }} deployed via GitHub Actions"
