name: Close Linked Issue

on:
  pull_request:
    types:
      - closed

jobs:
  close_issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close linked issues
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || '';

            const issuePattern = /close\s+#(\d+)/gi;
            const matches = [...prBody.matchAll(issuePattern)];

            if (matches.length === 0) {
              console.log('No linked issues found.');
              return;
            }

            for (const match of matches) {
              const issueNumber = match[1];
              console.log(`Closing issue #${issueNumber}`);

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: Number(issueNumber),
                state: 'closed',
              });
            }
